config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "application#home"

  # As neiter the 'users' nor the 'orgs' module are namespaced,
  #   pathes and 'as: :names' in them have to be uniquely named.
  #   e.g. you can not define get "/settings" in both modules and expect it to work.
  #
  scope module: :users, path: "/" do
    resource :session, only: %i[ new create destroy ]
    resources :passwords, param: :token, only: %i[ new create edit update ]

    get "/preferences", to: "preferences#show"

    patch "dark_mode", to: "display_modes#dark"
    patch "light_mode", to: "display_modes#light"
    patch "system_mode", to: "display_modes#system"
  end

  # resources :switch_current_organizations, only: %i[index show create destroy]
  get "open/:slug_org(/:slug_project)", to: "switch_orgs#switch_to", as: :open

  scope module: :orgs, path: "/" do
    # resources :days, only: %i[ index show ] # TODO: ensure these are unused now
    resources :entries, only: %i[ index create update ]
    resources :projects, param: :slug, only: %i[ index show ]

    get "settings", to: "settings#show"
  end

  # namespace :admin do
  #   mount MissionControl::Jobs::Engine, at: "/jobs"
  # end

  # keep this at the bottom of the routes file
  # catch all unknown routes to NOT throw a FATAL ActionController::RoutingError
  match "*path", to: "application#error_404", via: :all,
    constraints: ->(request) { !request.path_parameters[:path].start_with?("rails/") }
end

app/models/entry.rb
class Entry < ApplicationRecord
  STATES = %w[todo doing done].freeze

  belongs_to :day
  belongs_to :org
  belongs_to :member

  has_one :project, through: :day

  before_validation :set_org

  validates :log, presence: true
  validates :status, presence: true, inclusion: { in: STATES }

  def todo?
    status == "todo"
  end

  def doing?
    status == "doing"
  end

  def done?
    status == "done"
  end

  def today?
    Time.current.to_date == day.date # TODO: timezone correction
  end

  def future?
    Time.current.to_date < day.date # TODO: timezone correction
  end

  def past?
    Time.current.to_date > day.date # TODO: timezone correction
  end

  private

  def set_org
    self.org ||= day.org
  end
end

app/models/org.rb
class Org < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :days, dependent: :destroy
  has_many :integrations, dependent: :destroy
  has_many :members, inverse_of: :org, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :record_histories, dependent: :destroy

  has_many :users, through: :members

  before_create :set_slug

  validates :name, presence: true, uniqueness: true

  private

  def set_slug
    new_slug = name.parameterize

    new_slug = "#{new_slug}-#{rand(99)}" while Org.exists?(slug: new_slug)

    self.slug = new_slug
  end
end

app/controllers/orgs/days_controller.rb
module Orgs
  class DaysController < ApplicationController
    #
    # TODO: check if it was completely replaced by the entries controller
    #
    def index
      # @mode = params[:mode] || "edit"
      # @date = Date.parse(params[:date]) rescue Time.current.to_date

      # if params[:date] # basically like show, but initializes a new day if none exists for the date
      #   @day =
      #     current_project.days.includes(entries: :member).find_by(date: params[:date]) ||
      #       current_project.days.build(org: current_org, date: params[:date] || Time.current.to_date)

      #   @entries = sorted_entries(@day)

      #   render :show
      # elsif params[:member_id] # show all days of the current_project for the given member
      #   @members = current_project.members.order(name: :asc).pluck(:id, :name)
      #   @member = current_project.members.find(params[:member_id])
      #   @entries = current_project.entries.joins(:day).where(member: @member).order("day.date desc, entries.status desc", "entries.created_at asc")

      #   render :index_of_one_member
      # else
      #   @days = current_project.days
      # end
    end

    #
    # TODO: check if it was completely replaced by the entries controller
    #
    def show
      # @mode = params[:mode] || "edit"
      # @day = Day.includes(entries: :member).find(params[:id])
      # @entries = sorted_entries(@day)
    end

    private

    # TODO: copy sorting to entries_controller ?!
    def sorted_entries(day)
      day.entries.joins(:member).order("entries.status desc", "members.name asc", "entries.created_at asc")
    end
  end
end

app/controllers/orgs/entries_controller.rb
module Orgs
  class EntriesController < ApplicationController
    # when no day for the selected date exists yet, we initialize a new day,
    #   so the user can start typing a log immediately
    #
    # TODO: make the entries#index action the central point of the app
    #       * filter always by current_organization
    #       * filter optionally by date
    #       * filter optionally by project (if not given, restrict non-owners to participations)
    #       * filter optionally by member
    #       * filter optionally by status
    #       * group by date, project, status, member - enable to change order (and display of columns)
    #       * order("days.date desc", "days.project_id asc", "entries.status desc", "entries.member_id asc", "entries.created_at asc")
    #       * editable form or read-only view
    #
    # TODO: cleanup, extract, simplify!
    #
    # Ensure there is always 1 defined project, either current_project or @project from project_id!
    #
    def index
      date # to initialize it
      @group_by = group_by
      @with_date = params[:date].blank?
      @with_member = params[:member_id].blank?
      @with_project = current_project.blank? || params[:project_id].present? # TODO: display always ?!
      # TODO: or handle only current_project in this controller and leave the rest for the projects_controller ?!

      if params[:member_id]
        @member = project.members.find(params[:member_id])
        @members = project.members.order(:name).pluck(:id, :name)
      end

      # TODO: ensure edit mode always uses current_project OR makes it obvious & switches to project!!!
      if mode == "edit"
        @day =
          days.find_by(date: params[:date]) || days.build(org: current_org, date: params[:date] || Time.current.to_date)

        @entries =
          editable_entries(member: current_member, entries: @day.entries)
            .order(status: :desc, created_at: :asc)
      elsif mode == "read"
        date_days = days
        date_days = date_days.where(date: params[:date]) if params[:date]
        @entries = current_org.entries.where(day: date_days).order(status: :desc, created_at: :asc)
        @entries = @entries.where(member: @member) if @member
      end
    end

    # create_params[:date] is coming from a hidden form field and contains either
    #   the day's date or the date given in the URL.
    #   Therefore we need to find or create a day for the given date.
    #
    def create
      entry = Entry.new(
        org: current_org,
        member: current_member,
        day: current_project.days.find_or_create_by!(org: current_org, date: create_params[:date]),
        log: create_params[:log],
        status: create_params[:status] || "todo", # TODO
      )

      entry.save!

      redirect_to entries_path(date: entry.day.date, mode: "edit")
    end

    def update
      entry = current_project.entries.find(params[:id])

      entry.status = update_params[:status]  if update_params[:status].present?
      entry.log    = update_params[:log]     if update_params[:log].present?

      entry.save!

      redirect_to entries_path(date: entry.day.date, mode: "edit")
    end

    private

    def mode
      @mode ||= params[:mode] || "read"

      raise ArgumentError, "invalid mode: #{@mode}" unless %w[read edit].include?(@mode)

      @mode
    end

    def date
      @date ||= Date.parse(params[:date]) rescue Time.current.to_date
    end

    def days
      @days ||= current_org.days.where(project:)
    end

    def project
      @project ||=
        if params[:project_id]
          current_org.projects.find(params[:project_id])
        else
          current_project
        end

      raise ArgumentError, "no project given" if @project.blank?

      @project
    end

    def group_by
      return params[:group_by] if params[:group_by]
      return "date" if params[:date]
      return "member" if params[:member_id]
      return "project" if params[:project_id] # TODO: use slug

      nil
    end

    def readable_entries(member:, entries:)
      participant(member:).readable_entries(relation: entries)
    end

    def editable_entries(member:, entries:)
      # TODO: ensure participant.owner can see who's entries they edit
      # @with_member = participant(member:).roles.include?("owner")

      participant(member:).editable_entries(relation: entries)
    end

    def participant(member:)
       @participant ||= member.participations.find_by(project:)
    end

    def create_params
      params.require(:entry).permit(:date, :log, :status)
    end

    def update_params
      params.require(:entry).permit(:log, :status)
    end
  end
end

app/controllers/orgs/members_controller.rb
module Orgs
  class MembersController < ApplicationController
    #
    # TODO: before_action :authenticate_owner!, except: [:index]
    #
    def index
      # TODO: list all members of the organization
    end

    def create
      # TODO: add member to organization / status: invited?! (or unarchive member)
    end

    # TODO: add or remove member roles
    def update
      member = current_org.members.find(update_params[:member_id])

      invalid_roles = update_params[:roles] - Member::VALID_ROLES

      if invalid_roles.any?
        @error_message =
          "Member #{member.name} could not be updated to #{update_params[:roles].join(', ')}, " \
          "as it contains the invalid_roles: #{invalid_roles.join(', ')}"

      # render error
      else
        member = update_roles(member, update_params[:roles])

        # member.save and render success (or failure)
      end
    end

    def destroy
      # TODO: remove member from organization / archive member!
    end

    private

    def update_roles(member, new_roles)
      roles_to_remove = Member::VALID_ROLES - new_roles
      roles_to_set    = Member::VALID_ROLES & new_roles

      roles_to_remove.each { |role| member.delete_role(role) }
      roles_to_set.each    { |role| member.add_role(role) }

      member
    end

    def create_params
      params.expect(:member).permit(:org_id, :user_id)
    end

    def update_params
      params.expect(:member).permit(:member_id, :status, :roles)
    end
  end
end

app/controllers/orgs/projects_controller.rb
module Orgs
  class ProjectsController < ApplicationController
    def show
      # TODO: only display:
      #  * projects the member is participant of
      #  * all projects of org, if the member role is owner

      @project = current_org.projects.find_by!(slug: params[:slug])
      @entries_count = @project.entries.size

      @with_date = true
      @with_project = false
      @with_member = true

      # ONE project, many days
      @days =
        @project.days
          .includes(entries: :member)
          .order("days.date desc", "entries.status desc", "entries.member_id asc", "entries.created_at asc")

      # ALL the projects, many days
      #
      # TODO: move this code to the Entries controller
      #
      # TODO: add filters for project, day, member, status
      #
      # TODO: allow to configure sorting order: date, project, member (should change column order)
      #
      # TODO: add pagination
      #
      # @days = current_org.days.includes(:project, entries: :member)
      #   .order("days.date desc", "days.project_id asc", "entries.status desc", "entries.member_id asc", "entries.created_at asc")
    end

    def index
      if current_org
        @projects = current_org.projects.order(:name)
      else
        redirect_to root_path, notice: "Select an org first"
      end
    end
  end
end

app/controllers/orgs/settings_controller.rb
module Orgs
  class SettingsController < ApplicationController
    def show
    end

    def edit
    end
  end
end

app/views/orgs/entries/_editable_entry.html.erb
<!--
  Expects the following local variables:

  * entry
-->

<%= form_with(model: entry, data: { turbo_method: :patch }) do |form| %>
  <div role="group">
    <%= form.text_field :log, required: true, value: entry.log, minlength: 3, maxlength: 500 %>
    <%- # TODO: prevent losing edited log, when clicking on button instead of enter %>
    <%= link_to "todo", entry_path(entry, entry: { status: "todo" }), data: { turbo_method: :patch }, role: "button", class: "#{entry.todo? ? 'btn-todo' : 'btn-inactive'} btn-tdd" %>
    <%= link_to "doing", entry_path(entry, entry: { status: "doing" }), data: { turbo_method: :patch }, role: "button", class: "#{entry.doing? ? 'btn-doing' : 'btn-inactive'} btn-tdd" %>
    <%= link_to "done", entry_path(entry, entry: { status: "done" }), data: { turbo_method: :patch }, role: "button", class: "#{entry.done? ? 'btn-done' : 'btn-inactive'} btn-tdd" %>
  </div>
<% end %>

app/views/orgs/entries/_entries_nav_by_date.html.erb
<!--
  Expects the following local variables:

  * day
  * mode read | edit
-->

<div class="spacing-grid" style="margin-bottom: 0.5rem;">

  <div class="left">
    <h2> Day <%= date.iso8601 %> </h2>
  </div>

  <div class="center">
    <% if mode == "read" %>

      <% if @project && @project.participants.find_by(member: current_member) && @project != current_project %>
        <%= link_to "Switch to project '#{@project.name}' to add or edit", open_path(@project.org.slug, @project.slug), method: :get, role: "button", class: "slim" %>
      <% elsif current_project %>
        <%= link_to "add or edit", entries_path(date: date, mode: "edit"), method: :get, role: "button", class: "slim" %>
      <% end %>

    <% elsif mode == "edit" %>
      <%= link_to "view all", entries_path(date: date, mode: "read"), method: :get, role: "button", class: "slim" %>

    <% else %>
      mode '<%= mode %>' is invalid

    <% end %>
  </div>

  <div class="right">
    <%= link_to "⬅️", entries_path(date: date - 1.day, mode: mode, project_id: @project&.id), method: :get, role: "button", class: "slim" %>
    <%= link_to "➡️", entries_path(date: date + 1.day, mode: mode, project_id: @project&.id), method: :get, role: "button", class: "slim" %>
  </div>

</div>

app/views/orgs/entries/_entries_nav_by_member.html.erb
<!--
  Expects the following local variables:

  * member
  * members
  * mode read | edit
-->

<div class="spacing-grid" style="margin-bottom: 0.5rem;">

  <div class="left">
    <h2> Entries of <%= member.name %> </h2>
  </div>

  <div class="center">
    <% if mode == "read" %>

      <% if @project && @project.participants.find_by(member: current_member) && @project != current_project %>
        <%= link_to "Switch to project '#{@project.name}' to add or edit", open_path(@project.org.slug, @project.slug), method: :get, role: "button", class: "slim" %>
      <% elsif current_project %>
        <%= link_to "add or edit", entries_path(date: Time.current.to_date, mode: "edit"), method: :get, role: "button", class: "slim" %>
      <% end %>

    <% elsif mode == "edit" %>
      <%= link_to "view all", entries_path(member_id: member.id, mode: "read"), method: :get, role: "button", class: "slim" %>

    <% else %>
      mode '<%= mode %>' is invalid

    <% end %>
  </div>

  <div class="right">
    <% binding%>
    <% member_index = members.find_index { |k, _v| k == member.id } %>
    <% next_member_id = members[member_index + 1] ? members[member_index + 1][0] : members[0][0] %>
    <% previous_member_id = members[member_index - 1] ? members[member_index - 1][0] : members[0][0] %>

    <%= link_to "⬅️", entries_path(member_id: next_member_id, mode: "read", project_id: @project&.id), method: :get, role: "button", class: "slim" %>
    <%= link_to "➡️", entries_path(member_id: previous_member_id, mode: "read", project_id: @project&.id), method: :get, role: "button", class: "slim" %>
  </div>

</div>

app/views/orgs/entries/_entry.html.erb
<!--
  Expects the following local variables:

  * entry
  * entries
  * index
  * with_member (boolean)
  * with_date (boolean)
-->

<% grid_columns = 2 + (defined?(with_date) && with_date ? 1 : 0) + (defined?(with_project) && with_project ? 1 : 0) + (defined?(with_member) && with_member ? 1 : 0) %>
<div class="left-aligned-grid-<%= grid_columns %>">

  <% if defined?(with_date) && with_date %>
    <div class="left">
      <% if index == 0 || entry.day != entries[index - 1].day %>
        <h3 style="margin-top: -0.25rem;">
          <%= link_to entry.day.date.iso8601, entries_path(date: entry.day.date, project_id: @project&.id), method: :get, class: "camouflage s-link" %>
        </h3>
      <% end %>
    </div>
  <% end %>

  <% if defined?(with_project) && with_project %>
    <div class="left">
      <% if index == 0 || entry.project != entries[index - 1].project %>
        <h3 style="margin-top: -0.25rem;">
          <%= link_to entry.project.name, project_path(entry.day.project.slug), method: :get, class: "camouflage s-link" %>
        </h3>
      <% end %>
    </div>
  <% end %>

  <% if defined?(with_member) && with_member %>
    <div class="left">
      <% if index == 0 || entry.member != entries[index - 1].member %>
        <h3 style="margin-top: -0.25rem;">
          <%= link_to entry.member.name, entries_path(member_id: entry.member_id, project_id: @project&.id), method: :get, class: "camouflage s-link" %>
        </h3>
      <% end %>
    </div>
  <% end %>

  <div class="left">
    <%= entry.log %>
  </div>

  <!-- TODO set disabled: true on links and adapt colors to pop more -->

  <div class="right">
    <%= link_to "todo", "", method: nil, role: "button", class: "slim #{entry.todo? ? 'btn-todo' : 'btn-inactive'}" %>
    <%= link_to "doing", "", method: nil, role: "button", class: "slim #{entry.doing? ? 'btn-doing' : 'btn-inactive'}" %>
    <%= link_to "done", "", method: nil, role: "button", class: "slim #{entry.done? ? 'btn-done' : 'btn-inactive'}" %>
  </div>

</div>

app/views/orgs/entries/_new_entry.html.erb
<!--
  Expects the following local variables:

  * org
  * member
  * day
-->

<% new_entry = Entry.new(org:, member:, day:) %>

<%= form_with(model: new_entry, data: { turbo_method: :post }) do |form| %>
  <div role="group">
    <%= form.text_field :log, required: true, autofocus: true, placeholder: "What have you done today?", value: new_entry.log, minlength: 3, maxlength: 500 %>
    <%= form.hidden_field :date, value: @day.date %>
  </div>
<% end %>

app/views/orgs/entries/index.html.erb
<% if @group_by == "date" %>
  <%= render "orgs/entries/entries_nav_by_date", date: @date, mode: @mode %>
<% elsif @group_by == "member" %>
  <%= render "orgs/entries/entries_nav_by_member", member: @member, members: @members, mode: @mode %>
<% elsif @group_by == "project" %>
  <%= render "orgs/entries/entries_nav_by_project", project: @project, mode: @mode %>
<% else %>
  group_by '<%= @group_by %>' is invalid
<% end %>


<% if @mode == "edit" %>

  <ul class="bottom-spacer">
    <% @entries.each do |entry| %>
      <li class="nude tight">
        <%= render "orgs/entries/editable_entry", entry: entry %>
      </li>
    <% end %>

    <li class="nude">
      <%= render "orgs/entries/new_entry", org: current_org, member: current_member, day: @day %>
    </li>
  </ul>

<% elsif @mode == "read" %>
  <ul>
    <% @entries.each_with_index do |entry, index| %>
      <li class="nude">
        <%= render "orgs/entries/entry", entry: entry, entries: @entries, index: index, with_date: @with_date, with_member: @with_member, with_project: @with_project %>
      </li>
    <% end %>
  </ul>

<% else %>
  mode '<%= @mode %>' is invalid

<% end %>