config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "application#home"

  # As neiter the 'users' nor the 'orgs' module are namespaced,
  #   pathes and 'as: :names' in them have to be uniquely named.
  #   e.g. you can not define get "/settings" in both modules and expect it to work.
  #
  scope module: :users, path: "/" do
    resource :session, only: %i[ new create destroy ]
    resources :passwords, param: :token, only: %i[ new create edit update ]

    get "/preferences", to: "preferences#show"

    patch "dark_mode", to: "display_modes#dark"
    patch "light_mode", to: "display_modes#light"
    patch "system_mode", to: "display_modes#system"
  end

  # resources :switch_current_organizations, only: %i[index show create destroy]
  get "open/:slug_org(/:slug_project)", to: "switch_orgs#switch_to", as: :open

  scope module: :orgs, path: "/" do
    # resources :days, only: %i[ index show ] # TODO: ensure these are unused now
    resources :entries, only: %i[ index create update ]
    resources :projects, param: :slug, only: %i[ index show ]

    get "settings", to: "settings#show"
  end

  # namespace :admin do
  #   mount MissionControl::Jobs::Engine, at: "/jobs"
  # end

  # keep this at the bottom of the routes file
  # catch all unknown routes to NOT throw a FATAL ActionController::RoutingError
  match "*path", to: "application#error_404", via: :all,
    constraints: ->(request) { !request.path_parameters[:path].start_with?("rails/") }
end

app/views/layouts/_footer.html.erb
<footer>
  The End
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= content_for(:title) || "Done Today" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <% if AppConf.production_env? %>
    <%= stylesheet_link_tag "https://unpkg.com/@picocss/pico@latest/css/pico.amber.min.css", "data-turbo-track": "reload" %>
  <% else %>
    <%= stylesheet_link_tag "pico.amber.css", "data-turbo-track": "reload" %>
  <% end %>

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

app/views/layouts/_header.html.erb
<header>
  <%= render partial: "layouts/nav" %>
  <%= render partial: "shared_partials/flash_notifications" %>
</header>

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-grid">

    <div class="left">
      <h2>Done today</h2>
    </div>

    <div class="center zup">
      <% if current_user && current_project %>
        <%= render partial: "orgs/days/select" %>
      <% end %>
    </div>

    <div class="left">
      <% if current_user && current_user.memberships.any? %>
        <%= render partial: "shared_partials/org_switcher" %>
      <% end %>
    </div>

    <div class="right zup">
      <% if current_user %>
        <%= link_to "⚙", settings_path, method: :get, role: "button", class: "slim" %>
      <% end %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% if Current.display_mode %>
  <html data-theme="<%= Current.display_mode %>">
<% else %>
  <html>
<% end %>

  <%= render partial: "layouts/head" %>

  <body>

    <%= render partial: "layouts/header" %>

    <main>
      <%= yield %>
    </main>

    <%= render partial: "layouts/footer" %>

  </body>
</html>

app/views/layouts/logged_out.html.erb
<!DOCTYPE html>
<html>

  <%= render partial: "layouts/head" %>

  <body>

    <%= render partial: "layouts/header" %>

    <main>
      <div class="grid vgap">
        <div></div>
        <div>
          <%= yield %>
        </div>
        <div></div>
      </div>
    </main>

  <%= render partial: "layouts/footer" %>

  </body>
</html>